### ISSUE TITLE
Metal variant doesn't build by the manual

### ISSUE THREAD

**Issue by singalen** [thebracket/bracket-lib#188]
I try to follow this direction on Mac:
`If you want to use other rendering back-ends, disable default features and apply one of the following feature flags: [...] amethyst_engine_metal `

The following configuration doesn't build:
```
[dependencies.bracket-lib]
version = "~0.8.1"
default-features = false
features = ["amethyst_engine_metal"]
```
with an error:
```
   Compiling amethyst_animation v0.15.3
error[E0433]: failed to resolve: could not find `fmt` in `core`
  --> /Users/vic/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.15.3/src/app.rs:44:10
   |
44 | #[derive(Derivative)]
   |          ^^^^^^^^^^ could not find `fmt` in `core`
   |
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `fmt` in `core`
   --> /Users/vic/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.15.3/src/state.rs:366:10
    |
366 | #[derive(Derivative)]
    |          ^^^^^^^^^^ could not find `fmt` in `core`
    |
    = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `clone` in `core`
  --> /Users/vic/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.15.3/src/state_event.rs:17:17
   |
17 | #[derive(Debug, Derivative, EventReader)]
   |                 ^^^^^^^^^^ could not find `clone` in `core`
   |
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 3 previous errors
```

The default configuration builds and runs, but b/c of #109 it's hardly usable.
The same happens with the git version.

**Comment by thebracket** [comment]
I'm getting these errors compiling with Amethyst/Vulkan, also. Working on it now.

**Comment by thebracket** [comment]
It appears to relate to this bug: https://github.com/amethyst/amethyst/issues/2478

**Comment by singalen** [comment]
They mention there's a workaround: 
> We have to import std::core::fmt manually to workaround bug.

**Comment by thebracket** [comment]
I'm working on figuring out how to do that right now. :-)

**Comment by thebracket** [comment]
Doing some serious digging, it looks like I broke things when I adopted version 0.15 (which switches back-end to Legion). I'll have to do quite a bit of reworking to get 0.15.x running; so I'll schedule that, and try to get it working with 0.14 once more as a band-aid.

**Comment by singalen** [comment]
I'm personally fine with Mac on the current rendering back-end (is it OpenGL?). The only reason I tried it is in hope that #109 will go away.

**Comment by thebracket** [comment]
This is working for me on Windows and Linux (using Vulkan), so I believe the version pinning has done the job for now. Anyone want to check on a Mac for me? `cargo run --example astar_mouse --no-default-features --features amethyst_engine_metal`  should be the magic syntax.

**Comment by thebracket** [comment]
I *think* this is working now. I've successfully built Amethyst on Windows and Linux, and it built on my Mac VM (but won't run due to the VM not doing Metal properly). So I'm closing this - but if it continues to cause issues, please re-open.
